### PR TITLE
Add Docker environment & web demo

### PR DESCRIPTION
**Pull request by chenxwh**
Hey @YoadTew ! 👋 

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can try out your model! We have implemented the captioning model at the moment. View it here: https://replicate.com/yoadtew/zero-shot-image-to-text

We noticed you have signed up for [Replicate](https://replicate.ai/home), so you can add examples and customise the Example gallery as you like and push any future update to the web demo.

### CODE REVIEW

**Comment by YoadTew** [comment]
Thanks @CJWBW it looks great!

**Comment by YoadTew** [comment]
@CJWBW Hey, I see the cog.yaml and predict.py files from this pull requests are empty, do you have the files you used to create the web-page demo? We want to add more parameters tuning to the web-page :)

**Comment by chenxwh** [comment]
> @CJWBW Hey, I see the cog.yaml and predict.py files from this pull requests are empty, do you have the files you used to create the web-page demo? We want to add more parameters tuning to the web-page :)

hey @YoadTew I am so sorry, didn't realise those files were empty! I have opened a new PR with the added files. If you have any questions regarding pushing update to the wed demo, don't hesitate to write us! :)

**Comment by YoadTew** [comment]
@CJWBW No problem, thank you for uploading the files!

**Pull request merged**
